apiVersion: v1
kind: Service
metadata:
  name: flask-app-tutorial-service
spec:
  selector:
    name: flask-app-tutorial
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  type: LoadBalancer